### ISSUE TITLE
This software license

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [DISTRHO/DPF-Plugins#1]
Hi there!
I am preparing an Arch Linux PKGBUILD for this software. There isn't any license file in this repo. I looked up each single component and the licensing of them is not uniform. Most components are GPL or LGPL, but it appears that there are also MIT and ISC repos. The PKGBUILD license array is intended to contain multiple licenses that apply to the whole package in different cases rather than to different files in the package. As a result, I don't think I know how to provide correct licensing information for my package.

Could you please advise on the license under which the whole of this software is distributed?

(If this question does not have an answer I will resort to produce independent packages).

**Comment by falkTX** [comment]
This is a collection of plugins, so there's not 1 single license.
DPF is ISC, some plugins are GPL and some are LGPL.

**Comment by CrocoDuckoDucks** [comment]
Thank you for your prompt reply. I wish to rigorously comply to Arch packaging standards, so I will create a PKGBUILD for each single plugin, each one with its correct license.

**Comment by CrocoDuckoDucks** [comment]
Hi there again!
I asked for directions to the Arch Linux community. It is perhaps possible to include a LICENSE file in this repo that would make packaging easier, see [this thread](https://bbs.archlinux.org/viewtopic.php?pid=1675625#p1675625). In particular:

> adding some notes to the global readme / or a new global licensefile claryfing which code falls under which license, along with adding the individual licensefiles should be enough.
> 
> The [mesa license](http://mesa3d.org/license.html) shows an example of how this can be done.

Hope you find this feedback useful.

**Comment by falkTX** [comment]
Handled now.
Thanks for the initial work.
