### ISSUE TITLE
Build fails with projectM-3.1.11: fatal error: 'Intrinsics.h' file not found

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/DPF-Plugins#19]
Log: http://package19.nyi.freebsd.org/data/122amd64-default-build-as-user/566258/logs/dpf-plugins-lv2-1.4.log

**Comment by falkTX** [comment]
Not a problem with the plugins, they never include "Intrinsics.h", but the projectM headers instead.
So the issue will be on projectM.

**Comment by falkTX** [comment]
Furthermore, the plugin building makes use of pkg-config to set build flags, https://github.com/DISTRHO/DPF-Plugins/blob/master/plugins/ProM/Makefile#L29
So nothing else for the plugin to do here.

**Comment by yurivict** [comment]
Thanks!
