### ISSUE TITLE
Does the makefile allow separate builds?

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [DISTRHO/DPF-Plugins#2]
Hi there!
The [DISTRHO-Ports](https://github.com/DISTRHO/DISTRHO-Ports) makefile can be used to produce separate builds by passing build targets. For example `make vst` will only build vst plugins. I was wondering whether the current makefile for DPF-Plugins would allow the same. If not, would it be possible to add jack, vst, lv2, dssi and ladspa build targets?

**Comment by falkTX** [comment]
This is now possible, but everything is enabled by default.
To build just LADSPA  example, you need to do:
`make BUILD_DSSI=false BUILD_LV2=false BUILD_VST=false BUILD_JACK=false`
In my view, we should build the most formats as possible.

**Comment by falkTX** [comment]
Is what I proposed good for you?
If yes, please close the bug.
Thank you.

**Comment by falkTX** [comment]
I went back in my thoughts for this, the build for the different types is quite fast.
On a somewhat decent machine with `-j4`, it is just a few seconds to build the extra plugins.
I don't see a good reason for the partial builds, and it adds burden to maintain for me.
Closing as "won't fix".
