### ISSUE TITLE
dpf-plugins 1.6 armel build fails on debian sid: "Error: selected processor does not support `vmrs r3,fpscr' in ARM mode"

### ISSUE THREAD

**Issue by snd1** [DISTRHO/DPF-Plugins#23]
Heya :)

there is an build error with dpf-plugins 1.6 on armel:

```
{standard input}: Assembler messages:
{standard input}:202446: Error: selected processor does not support `vmrs r3,fpscr' in ARM mode
{standard input}:202448: Error: selected processor does not support `vmsr fpscr,r3' in ARM mode
```

A full log is here: https://buildd.debian.org/status/fetch.php?pkg=dpf-plugins&arch=armel&ver=1.6%2Bds-1&stamp=1671548666&raw=0

**Comment by falkTX** [comment]
that would mean ARM soft float, that would be too old to support in my opinion.
32bit ARM should at least support neon, so armv7 with hard-float target.

**Comment by falkTX** [comment]
btw, I see `libjack-dev | libjack-jackd2-dev` as dependency, that is not needed. jack is always enabled and uses a custom approach without system headers, with runtime detection and a fallback to rtaudio/midi if jack is not available.

also, libxcursor and libxrandr is missing. run "make features" before the build to see any other missing bits.
cairo and vulkan are unused for dpf-plugins, so you can ignore those

**Comment by snd1** [comment]
Thank you @falkTX i added these B-Ds and removed the libjack-dev B-D for now, will upload it to sid asap :smiley:
