### ISSUE TITLE
Cannot build ProM after latest updates

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [DISTRHO/DPF-Plugins#8]
Hi!
I used to be able to build all plugins with no issue up until r88. Now I cannot build ProM, not sure why as [projectm](https://www.archlinux.org/packages/community/x86_64/projectm/) is installed in my system. Seems like the make process is skipping ProM. This is the output of make all -C plugins/ProM:

```text
make: Entering directory '/home/crocoduck/DPF-Plugins/plugins/ProM'
Compiling DistrhoPluginProM.cpp
Compiling DistrhoUIProM.cpp
Compiling DistrhoPluginMain.cpp (JACK)
Compiling DistrhoUIMain.cpp (JACK)
Creating JACK standalone for ProM
/usr/bin/ld: ../../build/ProM/DistrhoPluginProM.cpp.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [../../dpf/Makefile.plugins.mk:127: ../../bin/ProM] Error 1
make: Leaving directory '/home/crocoduck/DPF-Plugins/plugins/ProM'
```
Since ProM used to build in the past, and the dependencies listed in the makefile (OpenGL, ProjectM) are installed in my system, I am wondering if anything is wrong with the makefile.

**Comment by falkTX** [comment]
I forgot to add the flags for that one.
Now fixed.

**Comment by CrocoDuckoDucks** [comment]
Nice. It works, but I still have to build ProM separately. That is, this is what I issue to build everything, including ProM:

```text
make all && make all -C plugins/ProM
```
Is this the expected behaviour?
