### ISSUE TITLE
More Problems as that of Issue #8: glBars

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [DISTRHO/DPF-Plugins#9]
Issue #8 was closed, but I am facing few additional problems.

First, to build ProM I have to issue this:

```text
make all && make all -C plugins/ProM
```
I believe that this is not expected, and `make all` should suffice.

Second, `make install` fails to install glBars:

```text
cp: cannot stat 'bin/glBars': No such file or directory
make: *** [Makefile:138: install] Error 1
```
However, glBars seems to be building correctly:

```text
make all -C plugins/glBars
make: Entering directory '/home/crocoduck/abs/.BuildTests/dpf-plugins-git/src/dpf-plugins/plugins/glBars'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/crocoduck/abs/.BuildTests/dpf-plugins-git/src/dpf-plugins/plugins/glBars'
```
Probably worth to mention that I found this out while working on [my AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dpf-plugins-git).

Any idea?

**Comment by falkTX** [comment]
Same as #10
Fixed in e7d0332c71ece4653fa207e2f1476a45fa98e1bf
